services:
  mysql:
    image: 'mysql:latest'
    user: mysql
    environment:
      - 'MYSQL_DATABASE=hms'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_USER=hmsuser'
    ports:
      - '3308:3306'
    volumes:
      - "${HOME}/var/lib/mysql/hms:/var/lib/mysql" # colima VM on mac