server:
    port: 8081

spring:
    datasource:
        url: "jdbc:mysql://localhost:3308/hms_dev"
        username: "hmsuser-dev"
        password: "hms.dev.123"
    flyway:
        enabled: true
        url: "jdbc:mysql://localhost:3308/hms_dev"
        user: "hms_migration_user"
        password: "hms.dev.migration.1234"
app:
    jwt-secret: "DaBcD3fGh1jKlMnOpQrStUvWxYz1234567890!@#$%^&*()"
    jwt-token-expired-time: 86400000
