server:
    servlet:
        context-path: /api
spring:
    profiles:
        active: @env@
    application:
        name: hms
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        enabled: true
    web:
        resources:
            add-mappings: false

app:
    jwt-issuer: hms