server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hms"
    username: hmsuser
    password: 1234
  flyway:
    enabled: true
#  devtools:
#    add-properties: false

