server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: hms
  datasource:
    url: "jdbc:mysql://localhost:3306/hms"
    username: hmsuser
    password: 1234
  flyway:
    enabled: true
  devtools:
    add-properties: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

