server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hms_dev"
    username: "hmsuser-dev"
    password: "hms.dev.123"
  flyway:
    enabled: true
    url: "jdbc:mysql://localhost:3306/hms_dev"
    user: "hms_migration_user"
    password: "hms.dev.migration.1234"
#  devtools:
#    add-properties: false

